name: Unzip to Root and Commit 2

on:
  workflow_dispatch:
    inputs:
      zip_filename:
        description: 'Nama file ZIP yang ingin diekstrak (contoh: file.zip)'
        required: true
        default: 'file.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install unzip
        run: sudo apt-get install unzip -y

      - name: Unzip the file to repo root
        run: |
          echo "Unzipping ${{ github.event.inputs.zip_filename }} to repo root"
          unzip -o "${{ github.event.inputs.zip_filename }}" -d ./

      - name: Commit and push extracted files to root
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .

          # Commit hanya jika ada perubahan
          git diff --cached --quiet || git commit -m "Unzipped ${{ github.event.inputs.zip_filename }} to root"

          git push origin HEAD
